"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from '@clerk/nextjs'
import {dark} from "@clerk/themes"
import {Inter} from 'next/font/google'
import { Navbar } from '../../components/NavBar';
const inter = Inter({subsets:["latin"]})
import Head from "next/head";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
  
    <Head>
        <link
          rel="preload"
          href="/_next/static/css/app/layout.css?v=1740543727546"
          as="style"
        />
      </Head>
    <ClerkProvider
    appearance={
      {
        baseTheme:dark
      }
    }
    >
      
      <html lang="en">
      <body
            
        className={`${inter.className} bg-black text-white antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
    
    </>
  );
}
